sonar.coverage.exclusions=\
**/jest.config.ts,\
**/setup-jest.ts,\
**/showcase/**,\
**/showcase/create/index.html,\
**/showcase/details/index.html,\
**/showcase/list/index.html,\
**/wc-prescription-details/test.utils.ts

sonar.exclusions=\
**/jest.config.ts,\
**/setup-jest.ts,\
**/showcase/**,\
**/showcase/create/index.html,\
**/showcase/details/index.html,\
**/showcase/list/index.html,\
**/wc-prescription-details/test.utils.ts
