sonar.coverage.exclusions=\
**/jest.config.ts,\
**/setup-jest.ts,\
**/showcase/**,\
**/showcase/create/index.html,\
**/showcase/details/index.html,\
**/showcase/list/index.html

sonar.exclusions=\
**/jest.config.ts,\
**/setup-jest.ts,\
**/showcase/**,\
**/showcase/create/index.html,\
**/showcase/details/index.html,\
**/showcase/list/index.html
