import { RequestStatus, Role } from '@reuse/code/openapi';
import { HttpStatusCode } from '@angular/common/http';
import { AlertType } from '@reuse/code/interfaces/alert.interface';

export interface ApiProblem {
  type: string;
  title: string;
  status: HttpStatusCode;
  detail: string;
  instance: string;
  properties: ApiProperties;
}

interface ApiProperties {
  code: string;
  subCode?: string;
  errorId?: string;
}

export interface ApiErrorPayload {
  code: string;
  status: HttpStatusCode;
  errorId?: string;
}

export interface ResolvedError {
  severity: AlertType;
  dismissible: boolean;
  retry: boolean;
  title?: string;
  message?: string;
  translationOptions?: Record<string, string | number>;
  subTitle?: string;
  errorId?: string;
}

export enum ApiCode {
  ACCESS_DENIED = 'ACCESS_DENIED',
  ACCESS_DENIED_DISCIPLINE = 'ACCESS_DENIED_DISCIPLINE',
  ACTION_ID_ALREADY_EXISTING = 'ACTION_ID_ALREADY_EXISTING',
  ACTION_ID_NOT_FOUND = 'ACTION_ID_NOT_FOUND',
  APPROVAL_NOT_POSSIBLE = 'APPROVAL_NOT_POSSIBLE',
  ASSIGNATION_DENIED_ADMIN = 'ASSIGNATION_DENIED_ADMIN',
  ASSIGNATION_NOT_POSSIBLE_WRONG_STATUS = 'ASSIGNATION_NOT_POSSIBLE_WRONG_STATUS',
  ATTACH_NOT_OWNER_OF_THE_BUNDLE = 'ATTACH_NOT_OWNER_OF_THE_BUNDLE',
  BUNDLE_NOT_FOUND = 'BUNDLE_NOT_FOUND',
  BUNDLE_NOT_OWNED = 'BUNDLE_NOT_OWNED',
  BUNDLE_NOT_OWNER_OF_PRESCRIPTION = 'BUNDLE_NOT_OWNER_OF_PRESCRIPTION',
  CANCEL_EXECUTION_NOT_IN_PROGRESS = 'CANCEL_EXECUTION_NOT_IN_PROGRESS',
  CANCELLATION_INVALID_STATUS = 'CANCELLATION_INVALID_STATUS',
  CAREGIVER_NO_RIGHT_CONSULTATION = 'CAREGIVER_NO_RIGHT_CONSULTATION',
  CAREGIVER_NOT_ASSIGNED_TO_ANY_PRESCRIPTION_OF_THE_BUNDLE = 'CAREGIVER_NOT_ASSIGNED_TO_ANY_PRESCRIPTION_OF_THE_BUNDLE',
  CAREGIVER_NOT_AVAILABLE_BEFORE = 'CAREGIVER_NOT_AVAILABLE_BEFORE',
  CAREGIVER_NOT_FOUND = 'CAREGIVER_NOT_FOUND',
  CAREGIVER_NOT_UNASSIGNABLE = 'CAREGIVER_NOT_UNASSIGNABLE',
  CONSULTRN_NOT_AVAILABLE = 'CONSULTRN_NOT_AVAILABLE',
  CREATION_DATE_FUTURE = 'CREATION_DATE_FUTURE',
  DATE_PROVIDED_AFTER_PRESCRIPTION_END_DATE = 'DATE_PROVIDED_AFTER_PRESCRIPTION_END_DATE',
  DECISION_ALREADY_TAKEN = 'DECISION_ALREADY_TAKEN',
  END_VALIDITY_DATE_PAST = 'END_VALIDITY_DATE_PAST',
  EXCLUSION_EXISTS = 'EXCLUSION_EXISTS',
  EXCLUSION_EXISTS_CAREGIVER_TO_ASSIGN = 'EXCLUSION_EXISTS_CAREGIVER_TO_ASSIGN',
  EXECUTION_DATE_FUTURE = 'EXECUTION_DATE_FUTURE',
  EXECUTION_NOT_USABLE = 'EXECUTION_NOT_USABLE',
  EXTENDED_NOT_FOUND = 'EXTENDED_NOT_FOUND',
  FEATURE_MUST_NOT_BE_USED = 'FEATURE_MUST_NOT_BE_USED',
  FINISH_EXECUTION_NOT_IN_PROGRESS = 'FINISH_EXECUTION_NOT_IN_PROGRESS',
  HEALTHCARE_PROFESSIONAL_ALREADY_ASSIGNED = 'HEALTHCARE_PROFESSIONAL_ALREADY_ASSIGNED',
  HEALTHCARE_PROFESSIONAL_NOT_AVAILABLE = 'HEALTHCARE_PROFESSIONAL_NOT_AVAILABLE',
  HEALTHCARE_PROFESSIONAL_NOT_OWNER = 'HEALTHCARE_PROFESSIONAL_NOT_OWNER',
  HEALTHCARE_PROFESSIONAL_NOT_OWNER_EXECUTION = 'HEALTHCARE_PROFESSIONAL_NOT_OWNER_EXECUTION',
  HEALTHCARE_PROFESSIONAL_TO_BE_ASSIGNED_MISSING_RIGHT = 'HEALTHCARE_PROFESSIONAL_TO_BE_ASSIGNED_MISSING_RIGHT',
  ID_DISCIPLINE_NOT_FOUND = 'ID_DISCIPLINE_NOT_FOUND',
  ID_INVALID = 'ID_INVALID',
  ID_SSIN_NOT_FOUND = 'ID_SSIN_NOT_FOUND',
  INCORRECT_VALIDITY_DATE = 'INCORRECT_VALIDITY_DATE',
  INTENT_INCORRECT_VALUE = 'INTENT_INCORRECT_VALUE',
  INVALID_COUNT_PARAMETER = 'INVALID_COUNT_PARAMETER',
  INVALID_DEPENDENCY = 'INVALID_DEPENDENCY',
  INVALID_EXECUTION_STATUS_CREATE = 'INVALID_EXECUTION_STATUS_CREATE',
  INVALID_HEALTH_CARE_PROFESSIONAL_ID = 'INVALID_HEALTH_CARE_PROFESSIONAL_ID',
  INVALID_ORGANIZATION_TASK_INFORMATION = 'INVALID_ORGANIZATION_TASK_INFORMATION',
  INVALID_PARAMETERS = 'INVALID_PARAMETERS',
  INVALID_PATIENT_BUNDLE = 'INVALID_PATIENT_BUNDLE',
  INVALID_PATIENT_REPLACEMENT = 'INVALID_PATIENT_REPLACEMENT',
  INVALID_PRESCRIPTION_STATUS = 'INVALID_PRESCRIPTION_STATUS',
  INVALID_STATUS_ASSIGNATION = 'INVALID_STATUS_ASSIGNATION',
  INVALID_STATUS_ATTACH = 'INVALID_STATUS_ATTACH',
  INVALID_TEMPLATE_DEFINITION = 'INVALID_TEMPLATE_DEFINITION',
  INVALID_TOKEN = 'INVALID_TOKEN',
  MALFORMED_ID = 'MALFORMED_ID',
  MISSING_ENCRYPTION_KEY = 'MISSING_ENCRYPTION_KEY',
  NO_MANDATE_FOR_PATIENT = 'NO_MANDATE_FOR_PATIENT',
  ORGANIZATION_ALREADY_ASSIGNED = 'ORGANIZATION_ALREADY_ASSIGNED',
  ORGANIZATION_NOT_ASSIGNABLE = 'ORGANIZATION_NOT_ASSIGNABLE',
  ORGANIZATION_NOT_UNASSIGNABLE = 'ORGANIZATION_NOT_UNASSIGNABLE',
  ORGANIZATION_TASK_NOT_FOUND = 'ORGANIZATION_TASK_NOT_FOUND',
  PATCH_NOT_APPLIED = 'PATCH_NOT_APPLIED',
  PATCH_WRONG_VALUE = 'PATCH_WRONG_VALUE',
  PRACTITIONER_NOT_FOUND = 'PRACTITIONER_NOT_FOUND',
  PRACTITIONER_ROLE_NOT_FOUND = 'PRACTITIONER_ROLE_NOT_FOUND',
  PRESCRIPTION_NOT_ASSIGNABLE = 'PRESCRIPTION_NOT_ASSIGNABLE',
  PRESCRIPTION_NOT_READABLE = 'PRESCRIPTION_NOT_READABLE',
  PSEUDONYMIZATION_ERROR = 'PSEUDONYMIZATION_ERROR',
  PSEUDONYMIZATION_INPUT_ERROR = 'PSEUDONYMIZATION_INPUT_ERROR',
  PSEUDONYMIZATION_PREFIX_NOT_RECOGNIZED = 'PSEUDONYMIZATION_PREFIX_NOT_RECOGNIZED',
  REFERENCE_NOT_EXISTING_IN_UHMEP = 'REFERENCE_NOT_EXISTING_IN_UHMEP',
  REJECTION_NOT_POSSIBLE = 'REJECTION_NOT_POSSIBLE',
  RELATIONSHIP_NOT_SUPPORTED = 'RELATIONSHIP_NOT_SUPPORTED',
  REQUEST_PARAMETER_NOT_MATCHING_TOKEN = 'REQUEST_PARAMETER_NOT_MATCHING_TOKEN',
  REQUIRED_SEARCH_CRITERIA_MISSING = 'REQUIRED_SEARCH_CRITERIA_MISSING',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  SELF_DEPENDENCY_NOT_ALLOWED = 'SELF_DEPENDENCY_NOT_ALLOWED',
  SERVICE_REQUEST_NOT_FOUND = 'SERVICE_REQUEST_NOT_FOUND',
  SERVICE_REQUEST_NOT_OWNED = 'SERVICE_REQUEST_NOT_OWNED',
  SERVICE_REQUEST_NOT_UNASSIGNABLE = 'SERVICE_REQUEST_NOT_UNASSIGNABLE',
  SERVICE_UNAVAILABLE_AA = 'SERVICE_UNAVAILABLE_AA',
  SSIN_NOT_FOUND = 'SSIN_NOT_FOUND',
  START_EXECUTION_DATE_AFTER_END_EXECUTION_DATE = 'START_EXECUTION_DATE_AFTER_END_EXECUTION_DATE',
  START_VALIDITY_DATE_AFTER_END_VALIDITY_DATE = 'START_VALIDITY_DATE_AFTER_END_VALIDITY_DATE',
  START_VALIDITY_DATE_PAST = 'START_VALIDITY_DATE_PAST',
  SUBJECT_REQUIRED_CREATION_BUNDLE = 'SUBJECT_REQUIRED_CREATION_BUNDLE',
  TASK_FOCUS_MISSING = 'TASK_FOCUS_MISSING',
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  TASKS_FOCUS_NOT_MATCHING = 'TASKS_FOCUS_NOT_MATCHING',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_SUSPENDED_ON_DATE_PROVIDED = 'USER_SUSPENDED_ON_DATE_PROVIDED',
  WRONG_REFERENCE_ORGANIZATION = 'WRONG_REFERENCE_ORGANIZATION',
  IMPLEMENTATION_GUIDE_VALIDATION_ERROR = 'IMPLEMENTATION_GUIDE_VALIDATION_ERROR',
  TERMINOLOGY_VALIDATION_ERROR = 'TERMINOLOGY_VALIDATION_ERROR',
}

export interface ErrorContext {
  serviceRequestStatus?: RequestStatus;
  role?: Role;
}
