export const NURSING_CODES = [
  'ASSISTING_WITH_PERSONAL_HYGIENE',
  'BLEEDING',
  'CHRONIC_PERITONEAL_DIALYSIS',
  'DIABETIC_EDUCATION_FOR_PATIENTS_WITH_CARE_PATH',
  'DIABETIC_EDUCATION_FOR_PATIENTS_WITH_MODEL_OF_CARE',
  'DIABETIC_EDUCATION_FOR_PATIENTS_WITHOUT_CARE_PATH',
  'DIABETIC_EDUCATION_VIA_CONVENTION_CENTER',
  'GLYCEMIC_TEST',
  'MEDICATION_PREFILL_PREPARATION',
  'MEDICATION_PREPARATION_PSYCHIATRIC_PATIENT',
  'PARAMETERS',
  'SAMPLING',
  'GENERIC'
];

export const RADIOLOGY_CODES = [
  'ANNEX_82'
];

export const PHYSIOTHERAPY_CODES = [
  'PHYSIOTHERAPY_CONSULTATIVE',
  'PHYSIOTHERAPY_GENERAL',
  'PHYSIOTHERAPY_PALLIATIVE',
  'PHYSIOTHERAPY_PERINATAL',
  'PHYSIOTHERAPY_TEMPOROMANDIBULAR_DYSFUNCTION'
];
